### ISSUE TITLE
Using ⭐️ 

### ISSUE THREAD

**Issue by dumindu** [ctjhoa/rust-learning#87]
By using ⭐️ do we give more favoritism for the resources created by rust team members even how much they are incomplete. Can't we use ⭐️ for suggesting best learning resources or do we have to use another Unicode like 🔥 instead ⭐️ to highlight resources created by rust team.

**Comment by ctjhoa** [comment]
> even how much they are incomplete.

What do you have in mind?

**Comment by cento** [comment]
You should classify the resources created by rust with a custom symbol and resources created in the last months (i.e., last 6 months) with another symbol. Rust is an evolving language, some old material could be less useful than the recent ones. 
Or, maybe, you could start to add a sort of "Release Date" for each new link.

**Comment by dumindu** [comment]
Hi @ctjhoa , 
I don't want to demotivate Rust team members or any other, just suggested this from a newcomers point of view.

**Comment by ctjhoa** [comment]
@dumindu
Okay to be clear. It's not about motivation.
The ⭐️icon gives favoritism on purpose, those resources has been created by the same guys who design the Rust language and Rust the ecosystem. It's totally fine to give more attention because they deserve it.
You talk about "best learning resources" but this is very subjective and I don't want to debate on each link if it's should be consider as "best" or not.
So ⭐️ represent an objective/clear way to help people to choose what's links are the most relevant and I will not change that.

If you have found incomplete link that's ok we could talk about it and decide if this specific resources should still be present.

@cento
> You should classify the resources created by rust team members with a custom symbol
That's what's ⭐️ is meant to be.

> You should classify the resources ... created in the last months with another symbol
Ok so here is the problems:
- I'm almost alone to maintain and organize this repo. So it could take me tremendous time to check each link regularly to see if there is updates or not. Moreover should updated resources considered as new or not?
- What about series of article like "Writing an OS in Rust" or "Arcade RS" should they be considered as new every time a new post is released?
- There is already a 🔚 icon which tag all links considered as obsolete. If you find that some links deserve this tag you could open a PR.

>  Rust is an evolving language; some old materials could be less useful than the recent ones.
Less useful maybe but Rust reach 1.0 so the language is stable. All resources written after May 2015 (Rust 1.0 release date) compile today even if there is more/new stuff in the language.

>  Alternatively, maybe, you could start to add a sort of "Release Date" for each new link.
It's pain in the *** for me for all reasons above.

**Comment by cento** [comment]
> That's what's ⭐️ is meant to be.

Now it is clear to me, thank you

> - I'm almost alone to maintain and organize this repo. So it could take me tremendous time to check each link regularly to see if there is updates or not. Moreover should updated resources considered as new or not?

I appreciate your work and your effort to maintain this page. Maybe a solution could be to start to insert the "release date" for newly added links and modify existing one if a "release date" exists, like the posting date, the published on youtube date, and so on. We can help.

> - What about series of article like "Writing an OS in Rust" or "Arcade RS" should they be considered as new every time a new post is released?

A "start date" should be enough 

> It's pain in the *** for me for all reasons above.

I understand what you mean. These are just ideas, feel free to consider them or not, of course. 
Anyway, your work is incredible, and it helps me so much in the past (and also today, to be honest). Very useful page, @ctjhoa

**Comment by ctjhoa** [comment]
@cento To conclude this issue I will take 2 actions:
- First do some cleanup on existing links (#97)
- Add "release date" in `Videos` to act like a test. (#98)

Feel free to contribute.
